In [72]:
import numpy as np
import scipy.io as sio

In [93]:
h =  np.vstack(np.arange(1,8,1))
for i in range(2,10):
    v = np.vstack(np.arange(i,i+7,1))
    h = np.concatenate((h,v),axis=1)
    
keys = np.array([4,3,2,1])
type(keys)

numpy.ndarray

In [117]:
h

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [125]:
h[:,1:2]

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [133]:
[bw, bh] = [2,2] #block size
[ofstW, ofstH] = [3,3] #offset from top left
[W,H] = [2,2] #block grid
grd = np.transpose(np.arange(1,W*H+1,1).reshape(W,H))
key = np.transpose(keys.reshape(W,H))

In [134]:
[H,W] = grd.shape

In [138]:
i=0
col = 1
row = 1

col_str = bh*i 
col_stp = bh+H 
row_str = bw 
row_stp = bw+W 
h[col_str:col_stp,row_str:row_stp]

array([[3, 4],
       [4, 5],
       [5, 6],
       [6, 7]])

In [139]:
keys[row]

3

In [141]:
#load key
mat_contents = sio.loadmat('permvec.mat')
permvec = mat_contents['permvec']
[Hp, Wp] = permvec.shape

In [178]:
permvec.astype(int).flatten()

array([ 7, 11,  3, 14,  4, 16,  5, 15,  2,  6,  1, 10, 13,  9,  8, 12])

In [174]:
keys = np.array([3,2,6,5,4,1])

In [175]:
type(keys)

numpy.ndarray

In [176]:
keys

array([3, 2, 6, 5, 4, 1])

In [177]:
k = permvec[0:1,1:2]

In [172]:
k.astype(str).astype(int)

array([[11]])