In [5]:
from __future__ import division
import numpy as np
import scipy
from scipy import integrate
from numpy import linalg as LA

import pdb
import matplotlib.pyplot as plt

In [6]:
#import custom functions
#harmonic is assignment function
#sol_frame indexes array same as matlab

from harmonic import *
from sol_frame import *

In [21]:
#set up frame

#BC values for x
x0=-4
xN=4

delta_x = 1
x_frame = sol_frame(x0, xN, delta_x)
K = 1

In [22]:
#set up matrix A
a_dim = (len(x_frame)-1, len(x_frame)-1)
A = np.zeros(a_dim)

In [23]:
#add middle terms to matrix for central difference
for i in range(0, len(A)):
    #calculate x value at i
    x = 0

    A[i:(i+1),(i-1):i] = -1
    A[i:(i+1),i:(i+1)] = 2+K*(x**2)*delta_x**2
    A[i:(i+1),(i+1):(i+2)] = -1

In [24]:
A

array([[ 2., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  2., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  2.]])

In [25]:
[val, vect] = LA.eig(A)

In [26]:
vect[2]

array([-4.08248290e-01, -4.08248290e-01, -7.45393227e-16, -4.08248290e-01,
       -4.08248290e-01,  4.08248290e-01, -4.08248290e-01, -7.55290681e-17])

In [27]:
val

array([3.87938524, 3.53208889, 3.        , 2.34729636, 1.65270364,
       0.12061476, 0.46791111, 1.        ])